language: java

jdk:
  - oraclejdk8

script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package -B

after_success:
  - mvn integration-test jacoco:report coveralls:report

cache:
  directories:
    - '$HOME/.m2/repository'
